import fresh_tomatoes
import media
from collections import OrderedDict

gravity = media.Movie(
    "Gravity", "https://upload.wikimedia.org/wikipedia/en/f/f6/Gravity_Poster.jpg", "Dr. Ryan Stone (Sandra Bullock) is a medical engineer on her first shuttle mission. Her commander is veteran astronaut Matt Kowalsky (George Clooney), helming his last flight before retirement. Then, during a routine space walk by the pair, disaster strikes: The shuttle is destroyed, leaving Ryan and Matt stranded in deep space with no link to Earth and no hope of rescue. As fear turns to panic, they realize that the only way home may be to venture further into space.", 3.9, "https://www.youtube.com/watch?v=OiTiKOy59o4")

the_martian = media.Movie(
    "The Martian", "https://upload.wikimedia.org/wikipedia/en/c/cd/The_Martian_film_poster.jpg", "When astronauts blast off from the planet Mars, they leave behind Mark Watney (Matt Damon), presumed dead after a fierce storm. With only a meager amount of supplies, the stranded visitor must utilize his wits and spirit to find a way to survive on the hostile planet. Meanwhile, back on Earth, members of NASA and a team of international scientists work tirelessly to bring him home, while his crew mates hatch their own plan for a daring rescue mission.",4, "https://www.youtube.com/watch?v=ej3ioOneTy8")

interstellar = media.Movie(
    "Interstellar", "https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg", "In Earth's future, a global crop blight and second Dust Bowl are slowly rendering the planet uninhabitable. Professor Brand (Michael Caine), a brilliant NASA physicist, is working on plans to save mankind by transporting Earth's population to a new home via a wormhole. But first, Brand must send former NASA pilot Cooper (Matthew McConaughey) and a team of researchers through the wormhole and across the galaxy to find out which of three planets could be mankind's new home.", 4.3 ,"https://www.youtube.com/watch?v=ePbKGoIGAXY")
inception = media.Movie("Inception", "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg", "Dom Cobb (Leonardo DiCaprio) is a thief with the rare ability to enter people's dreams and steal their secrets from their subconscious. His skill has made him a hot commodity in the world of corporate espionage but has also cost him everything he loves. Cobb gets a chance at redemption when he is offered a seemingly impossible task: Plant an idea in someone's mind. If he succeeds, it will be the perfect crime, but a dangerous enemy anticipates Cobb's every move.", 4.4,
                        "https://www.youtube.com/watch?v=66TuSJo4dZM")
ex_machina = media.Movie("Ex Machina", "http://www.joblo.com/timthumb.php?src=/posters/images/full/ex-machina-poster.jpg&h=600&q=100", "Caleb Smith (Domhnall Gleeson) a programmer at a huge Internet company, wins a contest that enables him to spend a week at the private estate of Nathan Bateman (Oscar Isaac), his firm's brilliant CEO. When he arrives, Caleb learns that he has been chosen to be the human component in a Turing test to determine the capabilities and consciousness of Ava (Alicia Vikander), a beautiful robot. However, it soon becomes evident that Ava is far more self-aware and deceptive than either man imagined.", 3.85,
                         "https://www.youtube.com/watch?v=XYGzRB4Pnq8")
looper = media.Movie("Looper", "https://upload.wikimedia.org/wikipedia/en/0/0a/Looper_poster.jpg", "In a future society, time-travel exists, but it's only available to those with the means to pay for it on the black market. When the mob wants to eliminate someone, it sends the target into the past, where a hit man known as a looper lies in wait to finish the job. Joe (Joseph Gordon-Levitt) is one such hired gun, and he does his job well -- until the day his bosses decide to \"close the loop\" and send Joe's future self (Bruce Willis) back in time to be killed.", 3.7,
                     "https://www.youtube.com/watch?v=2iQuhsmtfHw")

dunkirk = media.Movie(
    "Dunkirk", "https://upload.wikimedia.org/wikipedia/en/1/15/Dunkirk_Film_poster.jpg", "In May 1940, Germany advanced into France, trapping Allied troops on the beaches of Dunkirk. Under air and ground cover from British and French forces, troops were slowly and methodically evacuated from the beach using every serviceable naval and civilian vessel that could be found. At the end of this heroic mission, 330,000 French, British, Belgian and Dutch soldiers were safely evacuated.", 4.25, "https://www.youtube.com/watch?v=T7O7BtBnsG4")
iron_man = media.Movie("Iron Man", "https://upload.wikimedia.org/wikipedia/en/7/70/Ironmanposter.JPG", "A billionaire industrialist and genius inventor, Tony Stark (Robert Downey Jr.), is conducting weapons tests overseas, but terrorists kidnap him to force him to build a devastating weapon. Instead, he builds an armored suit and upends his captors. Returning to America, Stark refines the suit and uses it to combat crime and terrorism.", 4.05,
                       "https://www.youtube.com/watch?v=8hYlB38asDY")
guardians_of_the_galaxy = media.Movie(
    "Guardians of the Galaxy", "https://upload.wikimedia.org/wikipedia/en/8/8f/GOTG-poster.jpg", "Brash space adventurer Peter Quill (Chris Pratt) finds himself the quarry of relentless bounty hunters after he steals an orb coveted by Ronan, a powerful villain. To evade Ronan, Quill is forced into an uneasy truce with four disparate misfits: gun-toting Rocket Raccoon, treelike-humanoid Groot, enigmatic Gamora, and vengeance-driven Drax the Destroyer. But when he discovers the orb's true power and the cosmic threat it poses, Quill must rally his ragtag group to save the universe.", 5, "https://www.youtube.com/watch?v=B16Bo47KS2g")
logan = media.Movie("Logan", "https://upload.wikimedia.org/wikipedia/en/3/37/Logan_2017_poster.jpg", "In the near future, a weary Logan (Hugh Jackman) cares for an ailing Professor X (Patrick Stewart) at a remote outpost on the Mexican border. His plan to hide from the outside world gets upended when he meets a young mutant (Dafne Keen) who is very much like him. Logan must now protect the girl and battle the dark forces that want to capture her.", 4.1,
                    "https://www.youtube.com/watch?v=Div0iP65aZo")
edge_of_tomorrow = media.Movie(
    "Edge of Tomorrow", "https://upload.wikimedia.org/wikipedia/en/f/f9/Edge_of_Tomorrow_Poster.jpg", "When Earth falls under attack from invincible aliens, no military unit in the world is able to beat them. Maj. William Cage (Tom Cruise), an officer who has never seen combat, is assigned to a suicide mission. Killed within moments, Cage finds himself thrown into a time loop, in which he relives the same brutal fight -- and his death -- over and over again. However, Cage's fighting skills improve with each encore, bringing him and a comrade (Emily Blunt) ever closer to defeating the aliens.", 3.95, "https://www.youtube.com/watch?v=yUmSVcttXnI")
spectre = media.Movie("Spectre", "https://s-media-cache-ak0.pinimg.com/originals/ca/50/f3/ca50f39c54e852d4bbf0ce572d7024f9.jpg",
                      "A cryptic message from the past leads James Bond (Daniel Craig) to Mexico City and Rome, where he meets the beautiful widow (Monica Bellucci) of an infamous criminal. After infiltrating a secret meeting, 007 uncovers the existence of the sinister organization SPECTRE. Needing the help of the daughter of an old nemesis, he embarks on a mission to find her. As Bond ventures toward the heart of SPECTRE, he discovers a chilling connection between himself and the enemy (Christoph Waltz) he seeks.", 3.4, "https://www.youtube.com/watch?v=z4UDNzXD3qA")

moonlight = media.Movie("Moonlight", "https://upload.wikimedia.org/wikipedia/en/8/84/Moonlight_%282016_film%29.png", "A look at three defining chapters in the life of Chiron, a young black man growing up in Miami. His epic journey to manhood is guided by the kindness, support and love of the community that helps raise him.", 3.75,
                        "https://www.youtube.com/watch?v=9NJj12tJzqc")
the_imitation_game = media.Movie(
    "The Imitation Game", "https://upload.wikimedia.org/wikipedia/en/5/5e/The_Imitation_Game_poster.jpg", "In 1939, newly created British intelligence agency MI6 recruits Cambridge mathematics alumnus Alan Turing (Benedict Cumberbatch) to crack Nazi codes, including Enigma -- which cryptanalysts had thought unbreakable. Turing's team, including Joan Clarke (Keira Knightley), analyze Enigma messages while he builds a machine to decipher them. Turing and team finally succeed and become heroes, but in 1952, the quiet genius encounters disgrace when authorities reveal he is gay and send him to prison.", 4.05, "https://www.youtube.com/watch?v=S5CjKEFb-sM")
bridge_of_spies = media.Movie(
    "Bridge of Spies", "https://upload.wikimedia.org/wikipedia/en/f/fa/Bridge_of_Spies_poster.jpg", "During the Cold War, the Soviet Union captures U.S. pilot Francis Gary Powers after shooting down his U-2 spy plane. Sentenced to 10 years in prison, Powers' only hope is New York lawyer James Donovan (Tom Hanks), recruited by a CIA operative to negotiate his release. Donovan boards a plane to Berlin, hoping to win the young man's freedom through a prisoner exchange. If all goes well, the Russians would get Rudolf Abel (Mark Rylance), the convicted spy who Donovan defended in court.", 3.8, "https://www.youtube.com/watch?v=2-2x3r1m2I4")
gone_girl = media.Movie("Gone Girl", "https://upload.wikimedia.org/wikipedia/en/0/05/Gone_Girl_Poster.jpg", "In Carthage, Mo., former New York-based writer Nick Dunne (Ben Affleck) and his glamorous wife Amy (Rosamund Pike) present a portrait of a blissful marriage to the public. However, when Amy goes missing on the couple's fifth wedding anniversary, Nick becomes the prime suspect in her disappearance. The resulting police pressure and media frenzy cause the Dunnes' image of a happy union to crumble, leading to tantalizing questions about who Nick and Amy truly are.", 4.05,
                        "https://www.youtube.com/watch?v=Ym3LB0lOJ0o")
the_wolf_of_wall_street = media.Movie(
    "The Wolf of Wall Street", "https://upload.wikimedia.org/wikipedia/en/1/1f/WallStreet2013poster.jpg", "In 1987, Jordan Belfort (Leonardo DiCaprio) takes an entry-level job at a Wall Street brokerage firm. By the early 1990s, while still in his 20s, Belfort founds his own firm, Stratton Oakmont. Together with his trusted lieutenant (Jonah Hill) and a merry band of brokers, Belfort makes a huge fortune by defrauding wealthy investors out of millions. However, while Belfort and his cronies partake in a hedonistic brew of sex, drugs and thrills, the SEC and the FBI close in on his empire of excess.", 4.1, "https://www.youtube.com/watch?v=iszwuX1AK6A")
prisoners = media.Movie("Prisoners", "https://upload.wikimedia.org/wikipedia/en/6/63/Prisoners2013Poster.jpg", "Keller Dover (Hugh Jackman) faces a parent's worst nightmare when his 6-year-old daughter, Anna, and her friend go missing. The only lead is an old motorhome that had been parked on their street. The head of the investigation, Detective Loki (Jake Gyllenhaal), arrests the driver (Paul Dano), but a lack of evidence forces Loki to release his only suspect. Dover, knowing that his daughter's life is at stake, decides that he has no choice but to take matters into his own hands.", 4.05,
                        "https://www.youtube.com/watch?v=sfRckdHq--c")

anchorman = media.Movie("Anchorman", "https://upload.wikimedia.org/wikipedia/en/6/64/Movie_poster_Anchorman_The_Legend_of_Ron_Burgundy.jpg", "Hotshot television anchorman Ron Burgundy (Will Ferrell) welcomes upstart reporter Veronica Corningstone (Christina Applegate) into the male-dominated world of 1970s broadcast news -- that is, until the talented female journalist begins to outshine Burgundy on air. Soon he grows jealous, begins a bitter feud with Veronica and eventually makes a vulgar slip on live TV that ruins his career. However, when an outrageous story breaks at the San Diego Zoo, Ron may get a chance to redeem himself.", 3.6,
                        "https://www.youtube.com/watch?v=Ip6GolC7Mk0")
superbad = media.Movie("Superbad", "https://upload.wikimedia.org/wikipedia/en/8/8b/Superbad_Poster.png", "High-school seniors Seth (Jonah Hill) and Evan (Michael Cera) have high hopes for a graduation party: The co-dependent teens plan to score booze and babes so they can become part of the in-crowd, but separation anxiety and two bored police officers (Bill Hader, Seth Rogen) complicate the pair's self-proclaimed mission.", 3.8,
                       "https://www.youtube.com/watch?v=4eaZ_48ZYog")
bridesmaids = media.Movie("Bridesmaids", "https://upload.wikimedia.org/wikipedia/en/d/df/BridesmaidsPoster.jpg", "Annie(Kristen Wiig) is a single woman whose own life is a mess, but when she learns that her lifelong best friend, Lillian(Maya Rudolph), is engaged, she has no choice but to serve as the maid of honor. Though lovelorn and almost penniless, Annie, nevertheless, winds her way through the strange and expensive rituals associated with her job as the bride's go - to gal. Determined to make things perfect, she gamely leads Lillian and the other bridesmaids down the wild road to the wedding.", 3.4, "https://www.youtube.com/watch?v=FNppLrmdyug")
tropic_thunder = media.Movie(
    "Tropic Thunder", "https://upload.wikimedia.org/wikipedia/en/d/d6/Tropic_thunder_ver3.jpg", "Tugg Speedman (Ben Stiller), pampered action superstar, sets out for Southeast Asia to take part in the biggest, most-expensive war movie produced, but soon after filming begins, he and his co-stars, Oscar-winner Kirk Lazarus (Robert Downey Jr.), comic Jeff Portnoy (Jack Black) and the rest of the crew, must become real soldiers when fighting breaks out in that part of the jungle.", 3.5, "https://www.youtube.com/watch?v=T-6YhRZowgc")
step_brothers = media.Movie(
    "Step Brothers", "https://upload.wikimedia.org/wikipedia/en/d/d9/StepbrothersMP08.jpg", "Brennan Huff (Will Ferrell) and Dale Doback (John C. Reilly) have one thing in common: they are both lazy, unemployed leeches who still live with their parents. When Brennan's mother and Dale's father marry and move in together, it turns the overgrown boys' world upside down. Their insane rivalry and narcissism pull the new family apart, forcing them to work together to reunite their parents.", 3.45, "https://www.youtube.com/watch?v=ANjenc4W1_Q")
the_hangover = media.Movie("The Hangover", "https://upload.wikimedia.org/wikipedia/en/b/b9/Hangoverposter09.jpg",
                           "Two days before his wedding, Doug (Justin Bartha) and three friends (Bradley Cooper, Ed Helms, Zach Galifianakis) drive to Las Vegas for a wild and memorable stag party. In fact, when the three groomsmen wake up the next morning, they can't remember a thing; nor can they find Doug. With little time to spare, the three hazy pals try to re-trace their steps and find Doug so they can get him back to Los Angeles in time to walk down the aisle.", 3.9, "https://www.youtube.com/watch?v=vhFVZsk3XEs")

science_fiction = media.Category("Science Fiction")
science_fiction.addMovies([interstellar, the_martian, gravity,
                           inception, ex_machina, looper])

action = media.Category("Action")
action.addMovies([dunkirk, iron_man, guardians_of_the_galaxy,
                  logan, edge_of_tomorrow, spectre])

drama = media.Category("Drama")
drama.addMovies([moonlight, the_imitation_game, bridge_of_spies,
                 gone_girl, the_wolf_of_wall_street, prisoners])

comedy = media.Category("Comedy")
comedy.addMovies([anchorman, superbad, bridesmaids,
                  tropic_thunder, step_brothers, the_hangover])

categories = media.Category.all_cats
fresh_tomatoes.open_movies_page(categories)
